// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, fs, path,
    _this = this;

  express = require('express');

  path = require('path');

  app = express();

  app.use(express.logger('dev'));

  app.use(express.bodyParser());

  app.use(app.router);

  app.use(express["static"](path.join(__dirname, 'public')));

  fs = require('fs');

  fs.readFile(path.join(__dirname + '/config.json'), function(err, data) {
    var AppSpot, EuropeanCB, OpenExchange, RatesController;
    if (err) {
      throw err;
    }
    data = JSON.parse(data);
    RatesController = require(path.join(__dirname + '/app/controllers/ratescontroller')).RatesController;
    OpenExchange = require(path.join(__dirname + '/app/models/openexchange')).OpenExchange;
    AppSpot = require(path.join(__dirname + '/app/models/appspot')).AppSpot;
    EuropeanCB = require(path.join(__dirname + '/app/models/ecb')).EuropeanCB;
    data.sources['openexchangerates.org']['class'] = OpenExchange;
    data.sources['appspot.com']['class'] = AppSpot;
    data.sources['ecb.int']['class'] = EuropeanCB;
    app.get('/api/rates', function(req, res) {
      var rates;
      rates = new RatesController();
      return rates.getRates(req, res, data.sources);
    });
    return app.listen(data.port, function() {
      return console.log('Express server listening on port 8080');
    });
  });

}).call(this);
