// Generated by CoffeeScript 1.6.3
(function() {
  var RatesController;

  RatesController = (function() {
    function RatesController() {}

    RatesController.prototype.getRates = function(req, res, sources) {
      var base, cur, getterInfo, limit, ratesCollection, sendRates, source, _results;
      cur = req.query.cur;
      base = req.query.base;
      ratesCollection = {};
      limit = 0;
      sendRates = this._sendRates;
      _results = [];
      for (source in sources) {
        getterInfo = sources[source];
        limit++;
        ratesCollection[source] = {};
        ratesCollection[source].error = false;
        ratesCollection[source].descriptions = [];
        _results.push((function(source, getterInfo) {
          var getter,
            _this = this;
          getter = new getterInfo['class'];
          getter.on('error', function(err) {
            console.log(source + ': ' + err);
            ratesCollection[source].error = true;
            return ratesCollection[source].descriptions.push(err);
          });
          getter.on('end', function(rates) {
            ratesCollection[source].rates = rates;
            getter = null;
            limit--;
            if (!limit) {
              return sendRates(res, base, cur, ratesCollection);
            }
          });
          return getter.getRates(base, cur, getterInfo.key);
        })(source, getterInfo));
      }
      return _results;
    };

    RatesController.prototype._sendRates = function(res, base, currencys, collection) {
      var cur, data, info, rate, ratesCollection, source, sources, _ref;
      console.log(collection);
      data = {};
      data.base = base;
      data.error = false;
      data.errors = {};
      ratesCollection = {};
      sources = [];
      for (source in collection) {
        info = collection[source];
        sources.push(source);
        if (info.error) {
          data.error = true;
          data.errors[source] = info.descriptions;
        }
        _ref = info.rates;
        for (cur in _ref) {
          rate = _ref[cur];
          if (ratesCollection[cur] == null) {
            ratesCollection[cur] = {};
          }
          ratesCollection[cur][source] = rate;
        }
      }
      data.ratesCollection = ratesCollection;
      data.sources = sources;
      return res.send(data);
    };

    return RatesController;

  })();

  exports.RatesController = RatesController;

}).call(this);
