// Generated by CoffeeScript 1.6.3
(function() {
  var AppSpot, Parser, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Parser = require(__dirname + '/parser').Parser;

  AppSpot = (function(_super) {
    __extends(AppSpot, _super);

    function AppSpot() {
      _ref = AppSpot.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppSpot.prototype.getRates = function(base, currencys, key) {
      var i, url, _i, _ref1, _results;
      url = 'http://currency-api.appspot.com/api/';
      this._curLength = currencys.length;
      this._ratesInfo.rates = {};
      _results = [];
      for (i = _i = 0, _ref1 = currencys.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        _results.push(this._getData(url + base + ("/" + currencys[i] + ".json?key=") + key));
      }
      return _results;
    };

    AppSpot.prototype._onError = function(err) {
      this._ratesInfo.error = true;
      this._ratesInfo.descriptions.push(err);
      if (!this._curLength) {
        return this.emit('end', this._ratesInfo);
      }
    };

    AppSpot.prototype._parse = function(data) {
      var e;
      this._curLength--;
      try {
        data = JSON.parse(data);
      } catch (_error) {
        e = _error;
        this._onError(e);
        return;
      }
      if (!data.success) {
        this._onError(data.message);
        return;
      }
      this._ratesInfo.rates[data.target] = data.rate;
      if (!this._curLength) {
        return this.emit('end', this._ratesInfo);
      }
    };

    return AppSpot;

  })(Parser);

  exports.AppSpot = AppSpot;

}).call(this);
