// Generated by CoffeeScript 1.6.3
(function() {
  var OpenExchange, Parser, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Parser = require(__dirname + '/parser').Parser;

  OpenExchange = (function(_super) {
    __extends(OpenExchange, _super);

    function OpenExchange() {
      _ref = OpenExchange.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    OpenExchange.prototype._init = function() {
      return this.getRates = this.getLatest;
    };

    OpenExchange.prototype.getLatest = function(base, currencys, key, https) {
      var url;
      if (https == null) {
        https = false;
      }
      url = "http" + (https ? 's' : '') + "://openexchangerates.org/api/";
      if (https) {
        this._get = (require('https')).get;
      }
      this._base = base;
      this._currencys = currencys;
      return this._getData(url + 'latest.json?app_id=' + key);
    };

    OpenExchange.prototype._parse = function(data) {
      var b, cost, e, i, _i, _ref1;
      try {
        data = JSON.parse(data);
      } catch (_error) {
        e = _error;
        this._onError(e);
        return;
      }
      if (data.error) {
        this._onError(data.description);
        return;
      }
      b = data.base;
      if (b !== this._base) {
        cost = data.rates[this._base];
        data.rates[b] = 1;
      }
      this._ratesInfo.rates = {};
      for (i = _i = 0, _ref1 = this._currencys.length; 0 <= _ref1 ? _i < _ref1 : _i > _ref1; i = 0 <= _ref1 ? ++_i : --_i) {
        this._ratesInfo.rates[this._currencys[i]] = Math.round(data.rates[this._currencys[i]] / cost * 10000) / 10000;
      }
      return this.emit('end', this._ratesInfo);
    };

    return OpenExchange;

  })(Parser);

  exports.OpenExchange = OpenExchange;

}).call(this);
