// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter, Parser,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  Parser = (function(_super) {
    __extends(Parser, _super);

    function Parser() {
      var http;
      this._ratesInfo = {};
      this._ratesInfo.error = false;
      this._ratesInfo.descriptions = [];
      http = require('http');
      this._get = http.get;
      this._init();
    }

    Parser._init = function() {};

    Parser.prototype.getRates = function(base, currencys) {};

    Parser.prototype._getData = function(url) {
      var err,
        _this = this;
      try {
        return this._get(url, function(res) {
          var body;
          body = '';
          res.on('end', function() {
            if (body != null) {
              return _this._parse(body);
            } else {
              return _this._onError('Can\'t get data');
            }
          });
          return res.on('data', function(chunk) {
            return body += chunk;
          });
        }).on('error', function(e) {
          return _this._onError(e.message);
        });
      } catch (_error) {
        err = _error;
        return this._onError(err);
      }
    };

    Parser.prototype._onError = function(err) {
      this.emit(err);
      this._ratesInfo.error = true;
      this._ratesInfo.descriptions.push(err);
      return this.emit('end', this._ratesInfo);
    };

    Parser.prototype._parse = function(data) {};

    return Parser;

  })(EventEmitter);

  exports.Parser = Parser;

}).call(this);
