// Generated by CoffeeScript 1.6.3
(function() {
  var ForbiddenController;

  ForbiddenController = (function() {
    function ForbiddenController() {}

    ForbiddenController.prototype.errorSend = function(req, res) {
      var page;
      page = 'Page ' + req.path + 'not found';
      res.writeHead(404, {
        'content-type': 'text/html'
      });
      return res.send(page);
    };

    return ForbiddenController;

  })();

}).call(this);
