// Generated by CoffeeScript 1.6.3
(function() {
  var RatesController;

  RatesController = (function() {
    function RatesController() {}

    RatesController.prototype.getRates = function(req, res, sources) {
      var base, cur, getterInfo, source, _results;
      cur = req.query.cur;
      base = req.query.base;
      _results = [];
      for (source in sources) {
        getterInfo = sources[source];
        _results.push((function(source, getterInfo) {
          var getter,
            _this = this;
          getter = new getterInfo['class'];
          getter.on('error', function(err) {
            var data;
            console.log(source + ': ' + err);
            data = {};
            data.error = err;
            data.source = source;
            return res.send(data);
          });
          getter.on('end', function(rates) {
            var data;
            data = {};
            data.source = source;
            data.base = base;
            data.rates = rates;
            res.send(data);
            console.log(data);
            return getter = null;
          });
          return getter.getRates(base, cur, getterInfo.key);
        })(source, getterInfo));
      }
      return _results;
    };

    return RatesController;

  })();

  exports.RatesController = RatesController;

}).call(this);
